#!/bin/bash

prepare_args() {
    for i in "${@:2}"; do
        echo "--build-arg"
        echo "$i"
    done
}

print_tag_args() {
    line="$(cat ./tags-to-args | grep "$(print_tag) ")"
    prepare_args $line
}

print_version() {
    echo "$DOCKER_TAG" | grep -Po "^(\d.)+\d" || echo latest
}

print_tag() {
    echo "$DOCKER_TAG" | sed "s/$(print_version)-//"
}

print_build_args() {
    echo '--build-arg'
    echo VERSION="$(print_version)"
    print_tag_args
}

docker build $(print_build_args) -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
